#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define FISH_Z 0.5f
#define BACKGROUD_Z 1.0f

#define PI (3.1415926f)

#define FISH_KIND_NUM 6

#define NEEDLE_TEXTURE_INDEX 0
#define PARTICLE_TEXTURE_INDEX 1
#define DOLLAR_TEXTURE_INDEX 2
#define CONTROLPANEL_TEXTURE_INDEX 3
#define	NEEDLE2_TEXTURE_INDEX 4
#define BOMB_TEXTURE_INDEX 5
#define UNPLACED_BOMB_TEXTURE_INDEX 6
#define POW_TEXTURE_INDEX 7
#define LEFTFISH_TEXTURE_INDEX 8
#define RIGHTFISH_TEXTURE_INDEX 18
#define BLACK_LEFTFISH_TEXTURE_INDEX 28
#define BLACK_RIGHTFISH_TEXTURE_INDEX 38
#define CHANGE_WEAPON_BUTTON_TEXTURE_INDEX 48
#define CHANGE_WEAPON_BUTTON2_TEXTURE_INDEX 49
#define SMALL_NEEDLE_TEXTURE_INDEX 50
#define SMALL_BOMB_TEXTURE_INDEX 51
#define BUBBLE_TEXTURE_INDEX 52
#define DECELERATE_TEXTURE_INDEX 53
#define ACCELERATE_TEXTURE_INDEX 54
#define HARVEST_TEXTURE_INDEX 55
#define TREATURE_TEXTURE_INDEX 56
#define SKELETON_TEXTURE_INDEX 57
#define LIFE_TEXTURE_INDEX 58
#define WELCOME_TEXTURE_INDEX 59
#define MENUBUTTON_TEXTURE_INDEX 60
#define BLACK_TEXTURE_INDEX 61
#define TASKFAIL_TEXTURE_INDEX 62
#define LEFTTIME_TEXTRUE_INDEX 63
#define TASKGOAL_TEXTURE_INDEX 64
#define CONTINUEBUTTON_TEXTURE_INDEX 65
#define TASKFAIL_BUTTONS_TEXTURE_INDEX 66
#define TASKPASS_TEXTURE_INDEX 67
#define CUTSCENESTIP_BASE_TEXTURE_INDEX 68
#define CUTSCENES_BASE_TEXTURE_INDEX 88
#define PASS_ALL_TEXTURE_INDEX 108
#define ARCADE_TIMEOUT_TEXTURE_INDEX 109
#define ARCADEOVER_BUTTONS_TEXTURE_INDEX 110
#define FINAL_SCORE_TEXTURE_INDEX 111
#define OPENING_TITLE_TEXTURE_INDEX 112
#define ABOUT_TEXTURE_INDEX 113


#define MENU_BUTTON_SOUND 0
#define RUNNING_GAME_SOUND 1
#define CUTSCENE_SOUND 2
#define PUT_BOMB_SOUND 3
#define PUT_NEEDLE_SOUND 4
#define HIT_FISH_SOUND 5
#define BOMB_EXPLODE_SOUND 6

#define TOTAL_SCORE_POS_X 50
#define TOTAL_SCORE_POS_Y (SCREEN_HEIGHT - 50)

#define BOMB_SIZE_LENGTH 80
#define BOMB_MAX_RANGE 150



#define NEEDLE_WEAPON_TYPE 1
#define BOMB_WEAPON_TYPE 2

#define FIGHT_STATE 0
#define OPERATION_STATE 1
#define TASKFAIL_STATE 2
#define TASKPASS_STATE 3
#define ARCADEOVER_STATE 4


#define TREASURE_POSSIBILITY_INDEX 0
#define SKELETON_POSSIBILITY_INDEX 1
#define DECELERATE_POSSIBILITY_INDEX 2
#define ACCELERATE_POSSIBILITY_INDEX 3
#define HARVEST_POSSIBILITY_INDEX 4

#define ADD_FISH_TIME_INTERVAL 0.01f
#define ADD_PROP_TIME_INTERVAL 0.3f

#define BUBBLE_MOVE_STATE 0
#define BUBBLE_BURST_STATE 1
#define BUBBLE_ELAPSE_STATE 2
#define BUBBLE_DISAPPEAR_STATE 3

#define MAX_NEEDLE_VELOCITY 15.0f
#define MIN_NEEDLE_VELOCITY 2.0f
#define MAX_BOMB_COUNTDOWN 30
#define MIN_BOMB_COUNTDOWN 1

#define START_MENUBUTTON 0
#define ARCADE_MENUBUTTON 1
#define ABOUT_MENUBUTTON 2
#define EXIT_MENUBUTTON 3
#define CONTINUE_MENUBUTTON 4

#define START_MENUBUTTON_MSG 0
#define ARCADE_MENUBUTTON_MSG 1
#define ABOUT_MENUBUTTON_MSG 2
#define EXIT_GAME_MSG 3
#define CONTINUE_MENUBUTTON_MSG 4
#define TASKFAIL_MSG 5
#define BOMB_EXPLODE_MSG 6
#define BOMB_PLACED_MSG 7
#define RESTART_BARRIER_MSG 8
#define RETURN_MAINMENU_MSG 9
#define CHANGE_WEAPON_MSG 10
#define MOUSEOVER_CHANGEWEAPON_MSG 11
#define MOUSEOUT_CHANGEWEAPON_MSG 12
#define TASKPASS_MSG 13
#define NEXT_BARRIER_MSG 14
#define RESTART_ARCADE_MSG 15
#define ARCADE_OVER_MSG 16

#define TOTAL_BARRIER_COUNT 6
